# Generated by Django 3.2 on 2021-05-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('status', models.CharField(choices=[('PRO', 'PRO'), ('PLUS', 'PLUS'), ('PREMIUM', 'PREMIUM')], max_length=10, verbose_name='Status')),
                ('usuario', models.IntegerField(default=0, verbose_name='Quantidade Usuários')),
                ('armazenamento', models.CharField(max_length=10, verbose_name='Armazenamento')),
                ('suporte', models.CharField(max_length=30, verbose_name='Suporte')),
                ('atualização', models.CharField(max_length=30, verbose_name='Atualização')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
