# Generated by Django 3.2 on 2021-05-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preco',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
    ]
