# Generated by Django 3.2 on 2021-05-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_preco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preco',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços   '},
        ),
        migrations.RenameField(
            model_name='preco',
            old_name='atualização',
            new_name='atualizacao',
        ),
    ]
