# Generated by Django 3.2 on 2021-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210504_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=200, verbose_name='Bio'),
        ),
    ]
