# Generated by Django 3.2 on 2021-05-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], default=0, max_length=12, verbose_name='Icone'),
            preserve_default=False,
        ),
    ]
