# Generated by Django 3.2 on 2021-05-05 22:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_feature_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(default=0, upload_to='clientes/<function get_file_path at 0x00000268B28711F0>', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
